### ISSUE TITLE
A link is flagged erroneously

### ISSUE THREAD

**Issue by kolchfa-aws** [dblock/ruby-link-checker#9]
In our repo, one link is consistently flagged as broken by the link checker:  https://repost.aws/knowledge-center/ses-554-400-message-rejected-error. See, for example, this workflow run https://github.com/opensearch-project/documentation-website/actions/runs/5235192929/jobs/9451851728.

The solution might be to add a user agent.

**Comment by dblock** [comment]
To be clear it's not erroneous. A `curl https://repost.aws/knowledge-center/ses-554-400-message-rejected-error` fails with a 403. Specifying a user-agent does work around this.

**Comment by dblock** [comment]
This is coming from https://github.com/opensearch-project/documentation-website/issues/4301

**Comment by dblock** [comment]
Works as designed. Changing the user-agent works around the problem in https://github.com/opensearch-project/documentation-website/pull/4313.
